# Generated by Django 5.0.1 on 2024-02-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='overall',
            name='all_outcome',
            field=models.IntegerField(default=0),
        ),
    ]
