# Generated by Django 5.0.1 on 2024-02-11 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_productincome_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProdeuctIncoemoutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productincome')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productout')),
            ],
        ),
    ]
