# Generated by Django 5.0.1 on 2024-02-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_prodeuct_income_outcome_delete_prodeuctincoemoutcome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodeuct_income_outcome',
            new_name='Product_income_outcome',
        ),
    ]
