# Generated by Django 5.0.1 on 2024-02-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_prodeuct_income_outcome_product_income_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_income_outcome',
            name='foreign_id',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
