# Generated by Django 5.0.1 on 2024-02-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product_income_outcome_foreign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_income_outcome',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product_income_outcome',
            name='type',
            field=models.SmallIntegerField(),
        ),
    ]
