# Generated by Django 5.0.1 on 2024-02-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_product_income_outcome_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_income_outcome',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
