# Generated by Django 5.0.1 on 2024-02-11 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_product_income_outcome_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart'),
        ),
    ]
